# Generated by Django 4.0.1 on 2022-01-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finch',
            name='age',
        ),
    ]
